FROM php:8.3-fpm

ARG UID=1000
ARG GID=1000
ARG WITH_XDEBUG=false

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl unzip zip \
    libicu-dev libxml2-dev libzip-dev libonig-dev \
    default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

# Установка Node.js и npm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    pdo_mysql mbstring pcntl intl xml opcache zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN groupadd -g ${GID} appgroup \
    && useradd -u ${UID} -g appgroup -m appuser

# PROD
# эта важная команда для оптимизации при продакшене
#COPY . .

RUN mkdir -p storage bootstrap/cache \
    && chown -R appuser:appgroup storage bootstrap/cache

# PROD
# эта важная команда для оптимизации при продакшене
#RUN composer install --no-dev --optimize-autoloader

COPY opcache.ini /usr/local/etc/php/conf.d/opcache.ini
COPY www.conf /usr/local/etc/php-fpm.d/www.conf

RUN if [ "$WITH_XDEBUG" = "true" ]; then \
    pecl install xdebug && docker-php-ext-enable xdebug ; \
fi

USER appuser

EXPOSE 9000
