[www]

user = appuser
group = appgroup

; PHP-FPM слушает внутри контейнера
listen = 0.0.0.0:9000

; -------------------------
; 🚀 PROCESS MANAGEMENT (PROD)
; -------------------------

; В production НЕ static (это для dev/очень специфичных случаев)
; dynamic = лучший вариант для нагрузки
pm = dynamic

; минимальные и максимальные процессы
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 10

; сколько запросов обслуживает процесс до перезапуска
; защищает от memory leaks
pm.max_requests = 500

; -------------------------
; PERFORMANCE / NETWORK
; -------------------------

listen.backlog = 4096

; важно для high-load (если много коротких запросов)
request_terminate_timeout = 120s

; -------------------------
; 🐌 SLOW LOG (очень полезно в проде)
; -------------------------
slowlog = /proc/self/fd/2
request_slowlog_timeout = 5s

; -------------------------
; ⚠️ ENV (ВАЖНО)
; -------------------------

; APP_ENV=local

